name: Install and Run Global NPM Package for SVGO

on:
  push:
    branches:
      - main

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install global package
        run: npm install -g svgo

      - name: Run SVG Optimisation globally
        run:  svgo -rf .
